# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Generate Badge
      if: always()
      run: |
        echo ::set-output name=status::$(dotnet test --list-tests | grep "Total tests:" | awk '{ print $3 " tests" }')
        echo ::set-output name=color::$(dotnet test --list-tests | grep "Total tests:" | awk '{ if ($3 > 0) print "green"; else print "red" }')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit status
      if: always()
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Test status: ${{ env.status }}"
        prerelease: false
        files: ""
        asset_name: ""
        overwrite: true